---
- name: Download APM Server from S3
  amazon.aws.s3_object:
    bucket: "{{ s3_binaries_bucket }}"
    object: "apm-server-{{ elasticsearch_version }}-linux-x86_64.tar.gz"
    dest: "/tmp/apm-server.tar.gz"
    mode: get

- name: Extract APM Server
  ansible.builtin.unarchive:
    src: "/tmp/apm-server.tar.gz"
    dest: "/opt/elastic"
    remote_src: yes

- name: Configure APM Server
  ansible.builtin.template:
    src: apm-server.yml.j2
    dest: "/opt/elastic/apm-server-{{ elasticsearch_version }}-linux-x86_64/apm-server.yml"
    mode: '0644'
  notify: restart apm-server

- name: Start APM Server
  ansible.builtin.command: "/opt/elastic/apm-server-{{ elasticsearch_version }}-linux-x86_64/apm-server -e &"
  args:
    creates: "/opt/elastic/apm-server-{{ elasticsearch_version }}-linux-x86_64/logs/apm-server.log"