---
# Default variables for Fleet node role (Elastic Agent)
fleet_node_elastic_agent_version: "8.11.2"
fleet_node_elastic_agent_install_dir: "/opt/elastic-agent"
fleet_manager_url: ""
fleet_enrollment_token: ""
